{
  "success": false,
  "error": "Traceback (most recent call last):\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\platform\\solc.py\", line 559, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\slither\\__main__.py\", line 834, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\slither\\__main__.py\", line 87, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\crytic_compile.py\", line 641, in compile_all\n    compilations.append(CryticCompile(filename, **kwargs))\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\crytic_compile.py\", line 110, in __init__\n    self._compile(**kwargs)\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\crytic_compile.py\", line 530, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\platform\\solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\platform\\solc.py\", line 283, in _get_targets_json\n    return _run_solc(\n  File \"C:\\Users\\Yeort\\anaconda3\\lib\\site-packages\\crytic_compile\\platform\\solc.py\", line 563, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation usage: solc-select install [-h] [INSTALL_VERSIONS ...]\r\nsolc-select install: error: argument INSTALL_VERSIONS: Invalid version - only solc versions above '0.4.5' are available\r\nusage: solc-select install [-h] [INSTALL_VERSIONS ...]\r\nsolc-select install: error: argument INSTALL_VERSIONS: Invalid version - only solc versions above '0.4.5' are available\r\n\n",
  "results": {}
}